name: habo
description: Minimalistic habit tracker.

publish_to: "none"

version: 2.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Updated SDK for compatibility

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  table_calendar: ^3.0.9
  awesome_dialog: ^3.1.0
  loader_overlay: ^3.0.0
  introduction_screen: ^3.1.11
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  path: ^1.8.3
  fl_chart: ^0.64.0
  just_audio: ^0.9.34
  just_audio_mpv: ^0.1.7
  flutter_file_dialog: ^3.0.2
  file_picker:
    git:
      url: https://github.com/miguelpruivo/plugins_flutter_file_picker
      ref: master
  path_provider: ^2.1.0
  awesome_notifications: ^0.8.2
  timezone: ^0.9.2
  flutter_launcher_icons: ^0.13.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.5
  typed_data: ^1.3.0 # Fix for missing UnmodifiableUint8ListView in win32

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboard/
    - assets/sounds/
    - assets/google_fonts/


